### ISSUE TITLE
`SearchBar` doesn't propagate query string validation changes in case of auto submits

### ISSUE THREAD

**Issue by nilmerg** [Icinga/ipl-web#57]
## Bug

```
script 'hosts/index.phtml' not found in path (/usr/share/icingaweb2-modules/icingadb/application/views/scripts/)
#0 /icingaweb2/library/vendor/Zend/View/Abstract.php(873): Zend_View_Abstract->_script(String)
#1 /icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(String)
#2 /icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#3 /usr/local/src/ipl-web/src/Compat/ViewRenderer.php(47): Zend_Controller_Action_Helper_ViewRenderer->render(NULL, NULL, NULL)
#4 /icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): ipl\Web\Compat\ViewRenderer->render()
#5 /icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#6 /usr/share/icingaweb2-modules/icingadb/library/Icingadb/Web/Controller.php(744): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#7 /icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch(String)
#8 /icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /icingaweb2/library/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /icingaweb2/library/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#11 /icingaweb2/public/index.php(4): require_once(String)
#12 {main}
```

## To reproduce

* Visit `/icingaweb2/icingadb/hosts?state.soft_state=2|host.name=docker-master`
* Remove `host.name=docker-master` using the search bar
* Once the searchbar autosubmits, the error appears

**Comment by nilmerg** [comment]
refs https://github.com/Icinga/icingadb-web/issues/446
